apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: react-restaurant-landing-page-argocd
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/menghout009/react-restaurant-landing-page.git
    targetRevision: HEAD
    path: .
destination: 
    server: https://kubernetes.default.svc
    namespace: react

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true