apiVersion: v1
kind: Service
metadata:
  name: spring-service
spec:
  selector:
    app: spring
  type: NodePort
ports:
    - protocol: TCP
      port: 3000
      nodePort: 31001
      targetPort: 3000